# Generated by Django 4.2.7 on 2023-11-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='decription',
            new_name='description',
        ),
    ]
